// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJLdshnoDHB-YXV0CE5W4L-YiuZOlb44',
    appId: '1:637179097871:web:153e16dbdb514c3e19447a',
    messagingSenderId: '637179097871',
    projectId: 'cocoabeans-a8395',
    authDomain: 'cocoabeans-a8395.firebaseapp.com',
    storageBucket: 'cocoabeans-a8395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptd5cXwpXJrYbMmHBwDGKe_P56nCSUIc',
    appId: '1:637179097871:android:989cbdb95a0e975119447a',
    messagingSenderId: '637179097871',
    projectId: 'cocoabeans-a8395',
    storageBucket: 'cocoabeans-a8395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DA5uGAosZT3GNrzJTfOAaz5eXIXz-ag',
    appId: '1:637179097871:ios:a90ef42e1621fe6119447a',
    messagingSenderId: '637179097871',
    projectId: 'cocoabeans-a8395',
    storageBucket: 'cocoabeans-a8395.appspot.com',
    iosBundleId: 'com.example.cocoabeans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DA5uGAosZT3GNrzJTfOAaz5eXIXz-ag',
    appId: '1:637179097871:ios:7dc71e43d40d073a19447a',
    messagingSenderId: '637179097871',
    projectId: 'cocoabeans-a8395',
    storageBucket: 'cocoabeans-a8395.appspot.com',
    iosBundleId: 'com.example.cocoabeans.RunnerTests',
  );
}
